#requires -Version 7.0
#requires -RunAsAdministrator

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string] $AllowedPath,

    [Parameter(Mandatory)]
    [string] $PveIp,

    [ValidateRange(1024, 65535)]
    [int] $Port = 8082,

    [string] $ApiKey,

    [switch] $NoScheduledTask
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host 'DSH-LAN Windows Filesystem MCP setup (EXPERIMENTAL / NOT YET VALIDATED)'

$resolvedPath = (Resolve-Path -LiteralPath $AllowedPath).Path
if (-not (Test-Path -LiteralPath $resolvedPath -PathType Container)) {
    throw "AllowedPath must be an existing directory: $AllowedPath"
}

foreach ($cmd in 'node', 'npm') {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        throw "Missing $cmd. Install a current Node.js release first."
    }
}

$nodeMajor = [int]((node -p "process.versions.node.split('.')[0]").Trim())
if ($nodeMajor -lt 20) {
    throw "Node.js 20+ is required by this draft setup. Current: $(node -v)"
}

if (-not $ApiKey) {
    $bytes = [byte[]]::new(32)
    [Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $ApiKey = [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+','-').Replace('/','_')
}

if ($ApiKey -notmatch '^[A-Za-z0-9._~-]{16,128}$') {
    throw 'ApiKey must be 16-128 URL-safe characters: [A-Za-z0-9._~-]'
}

Write-Host 'Installing MCP packages globally...'
& npm install --global @modelcontextprotocol/server-filesystem mcp-proxy
if ($LASTEXITCODE -ne 0) { throw 'npm global install failed.' }

$proxy = (Get-Command mcp-proxy -ErrorAction Stop).Source
$filesystem = (Get-Command mcp-server-filesystem -ErrorAction Stop).Source

$base = Join-Path $env:LOCALAPPDATA 'dsh-lan\windows-files-mcp'
New-Item -ItemType Directory -Path $base -Force | Out-Null

$secretFile = Join-Path $base 'mcp-api-key.dpapi.txt'
$runnerFile = Join-Path $base 'run-files-mcp.ps1'
$configFile = Join-Path $base 'config.json'

# Keep the API key encrypted with Windows DPAPI for the current user.
$ApiKey | ConvertTo-SecureString -AsPlainText -Force | ConvertFrom-SecureString | Set-Content -LiteralPath $secretFile -Encoding utf8

[ordered]@{
    allowedPath = $resolvedPath
    pveIp       = $PveIp
    port        = $Port
    proxy       = $proxy
    filesystem  = $filesystem
} | ConvertTo-Json | Set-Content -LiteralPath $configFile -Encoding utf8

$runner = @'
# Auto-generated by dsh-lan setup-windows-files-mcp.ps1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$base = Split-Path -Parent $PSCommandPath
$config = Get-Content -LiteralPath (Join-Path $base 'config.json') -Raw | ConvertFrom-Json
$secure = Get-Content -LiteralPath (Join-Path $base 'mcp-api-key.dpapi.txt') -Raw | ConvertTo-SecureString
$ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
try {
    $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
}
finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
}

$env:MCP_PROXY_API_KEY = $plain

$proxyArgs = @(
    '--port', [string]$config.port,
    '--shell',
    '--',
    [string]$config.filesystem,
    [string]$config.allowedPath
)

& ([string]$config.proxy) @proxyArgs
exit $LASTEXITCODE
'@
Set-Content -LiteralPath $runnerFile -Value $runner -Encoding utf8

$ruleName = 'DSH-LAN Filesystem MCP'
Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue | Remove-NetFirewallRule
New-NetFirewallRule `
    -DisplayName $ruleName `
    -Direction Inbound `
    -Action Allow `
    -Protocol TCP `
    -LocalPort $Port `
    -RemoteAddress $PveIp `
    -Profile Private | Out-Null

if (-not $NoScheduledTask) {
    $taskName = 'DSH-LAN Filesystem MCP'
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue

    $pwsh = (Get-Command pwsh -ErrorAction Stop).Source
    $action = New-ScheduledTaskAction -Execute $pwsh -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$runnerFile`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Highest

    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal | Out-Null
    Start-ScheduledTask -TaskName $taskName
}
else {
    Start-Process -FilePath (Get-Command pwsh).Source -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File', $runnerFile)
}

# Determine the Windows source address that would be used to reach PVE.
$windowsIp = '<WINDOWS-LAN-IP>'
try {
    $udp = [Net.Sockets.UdpClient]::new()
    $udp.Connect($PveIp, 9)
    $windowsIp = ([Net.IPEndPoint]$udp.Client.LocalEndPoint).Address.IPAddressToString
    $udp.Dispose()
}
catch {
    Write-Warning 'Could not auto-detect Windows LAN IP.'
}

Start-Sleep -Seconds 2
try {
    $health = Invoke-WebRequest -UseBasicParsing -Uri "http://127.0.0.1:$Port/ping" -TimeoutSec 5
    Write-Host "mcp-proxy health: HTTP $($health.StatusCode)"
}
catch {
    Write-Warning "mcp-proxy health check did not pass yet: $($_.Exception.Message)"
}

Write-Host ''
Write-Host '============================================================'
Write-Host 'WINDOWS FILE MCP SETUP COMPLETE (DRAFT / NOT YET VALIDATED)'
Write-Host '============================================================'
Write-Host "Allowed directory : $resolvedPath"
Write-Host "Windows MCP URL   : http://${windowsIp}:$Port/mcp"
Write-Host "PVE allowlist     : $PveIp"
Write-Host "MCP X-API-Key     : $ApiKey"
Write-Host "Runner            : $runnerFile"
Write-Host ''
Write-Host 'Copy the API key into the PVE setup command. Do not publish it.'
Write-Host 'This draft uses HTTP for the MCP hop; keep it on a trusted LAN/VPN and do not expose it to the Internet.'
